

export const columns = [
  { field: "id", headerName: "ID" , width:33 , align: "center" , headerAlign:"center"},
  { field: "registerId", headerName: "Register ID" , width:100 , align: "center" , headerAlign:"center"},
  { field: "name", headerName: "Name" , align: "center" ,width:200, headerAlign:"center"},
  { field: "age", headerName: "Age" , type: "number",  width:110 ,align: "center" , headerAlign:"center"},
  { field: "phoneNumber", headerName: "Phone Number" , width:200 , align: "center" , headerAlign:"center"},
  { field: "email", headerName: "Email" ,width:200 , align: "center" , headerAlign:"center"},
  { field: "address", headerName: "Address" , width:250 , align: "center" , headerAlign:"center"},
  { field: "city", headerName: "City" , width:110 , align: "center" , headerAlign:"center"},
  { field: "zipCode", headerName: "Zip Code" , width:110 , align: "center" , headerAlign:"center"}
]


export const rows = [
  {
    id: 1,
    registerId: "254803",
    name: "William Davis",
    age: 35,
    phoneNumber: "(444)321-5654",
    email: "williamdavis@gmail.com",
    address: "2541 Maple Street",
    city: "London",
    zipCode: "10001",
  },
  {
    id: 2,
    registerId: "556300",
    name: "Benjamin Taylor",
    age: 48,
    phoneNumber: "(666)338-8544",
    email: "benjamintaylor@hotmail.com",
    address: "182 Greenfield Road",
    city: "Birmingham",
    zipCode: "52416",
  },
  {
    id: 3,
    registerId: "774106",
    name: "James Walker",
    age: 19,
    phoneNumber: "(666)844-4450",
    email: "jameswalker@yahoo.com",
    address: "76 Oxford Avenue",
    city: "Manchester",
    zipCode: "88900",
  },
  {
    id: 4,
    registerId: "996720",
    name: "Henry Clark",
    age: 29,
    phoneNumber: "(882)560-7710",
    email: "henryclark@gmail.com",
    address: "4210 Willow Lane",
    city: "Leeds",
    zipCode: "99304",
  },
  {
    id: 5,
    registerId: "88861",
    name: "Emily Brown",
    age: 33,
    phoneNumber: "(666)552-6330",
    email: "emilybrown@gmail.com",
    address: "93 Highfield Drive",
    city: "Bristol",
    zipCode: "74887",
  },
  {
    id: 6,
    registerId: "112487",
    name: "Jeo Snow",
    age: 51,
    phoneNumber: "(442)784-7742",
    email: "joesnow@gmail.com",
    address: "307 Parkside Crescent",
    city: "Liverpool",
    zipCode: "28146",
  },
  {
    id: 7,
    registerId: "123547",
    name: "Charlotte Harris",
    age: 21,
    phoneNumber: "(442)002-5106",
    email: "charlotte.harris@example.com",
    address: "1582 Kingsway Road",
    city: "Newcastle",
    zipCode: "12630",
  },
  {
    id: 8,
    registerId: "115570",
    name: "Olivia Smith",
    age: 62,
    phoneNumber: "(222)885-1245",
    email: "oliviasmith@gmail.com",
    address: "888 Rosewood Street",
    city: "Sheffield",
    zipCode: "10080",
  },
  {
    id: 9,
    registerId: "120059",
    name: "Sophia Wilson",
    age: 33,
    phoneNumber: "(442)636-0550",
    email: "sophiawilson@yahoo.com",
    address: "120 Victoria Square",
    city: "Nottingham",
    zipCode: "96322",
  },
  {
    id: 10,
    registerId: "788893",
    name: "Amelia Lewis",
    age: 39,
    phoneNumber: "(666)712-1776",
    email: "amelialewis@gmail.com",
    address: "645 Elm Grove",
    city: "Cambridge",
    zipCode: "87456",
  },
  {
    id: 11,
    registerId: "356841",
    name: "Daniel Johnson",
    age: 55,
    phoneNumber: "(222)963-2341",
    email: "danieljohnson@hotmail.com",
    address: "742 Evergreen Terrace",
    city: "London",
    zipCode: "11036",
  },
];